[package]
name = "iota-stronghold"
version = "0.1.0"
authors = ["Daniel Thompson-Yvetot <daniel.yvetot@iota.org>"]
edition = "2018"

[dependencies]
stronghold-engine = {path = "../engine"}

bincode = "1.3"
serde = {version = "1.0", features = ["derive"]}
anyhow = "1.0"
thiserror = "1.0"

riker = "0.4"

[workspace]
