[package]
name                    = "stronghold-runtime"
version                 = "0.1.0"
edition                 = "2021"
readme                  = "README.md"

[lib]
name                    = "runtime"
 
[dependencies]
zeroize                 = { version = "1.4.3" }
libsodium-sys           = { version = "0.2" }
serde                   = { version = "1.0", features = [ "derive" ] }
random                  = { version = "0.8.4", package = "rand" }
dirs                    = { version = "4.0.0" }
thiserror               = { version = "1.0" }
libc                    = { version = "0.2" }
log                     = { version = "0.4.17" }
iota-crypto             = { version = "0.8.0", features = ["blake2b"] }

[target.'cfg(windows)'.dependencies]
windows                 = { version = "0.36.0", features = ["Win32_System_Memory", "Win32_System_SystemInformation", "Win32_System_Diagnostics_Debug", "Win32_Foundation", "Win32_Security"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
nix                     = { version = "0.24.1" }

[dev-dependencies]
serde_json              = { version = "1.0" }
env_logger              = { version = "0.9" }