[package]
name = "new_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeroize = "1.5.0"
libsodium-sys = "0.2"
serde = { version = "1.0", features = [ "derive" ] }
