[package]
name = "store"
version = "0.2.0"
authors = ["tensor-programming <tensordeveloper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.1"
once_cell = "1.4"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false